export const colleges = [
  'American University',
  'Auburn University',
  'Baylor University',
  'Boston College',
  'Boston University',
  'Brandeis University',
  'Brigham Young University',
  'Brown University',
  'California Institute of Technology (Caltech)',
  'Carnegie Mellon University',
  'Case Western Reserve University',
  'Clemson University',
  'College of William & Mary',
  'Columbia University',
  'Cornell University',
  'Dartmouth College',
  'Drexel University',
  'Duke University',
  'Emory University',
  'Florida State University',
  'Fordham University',
  'George Washington University',
  'Georgetown University',
  'Georgia Institute of Technology',
  'Harvard University',
  'Indiana University Bloomington',
  'Johns Hopkins University',
  'Lehigh University',
  'Marquette University',
  'Massachusetts Institute of Technology (MIT)',
  'McGill University',
  'McMaster University',
  'Miami University',
  'Michigan State University',
  'North Carolina State University',
  'Northeastern University',
  'Northwestern University',
  'Ohio State University',
  'Pennsylvania State University',
  'Pepperdine University',
  'Princeton University',
  'Purdue University',
  "Queen's University",
  'Rensselaer Polytechnic Institute',
  'Rice University',
  'Rutgers University-New Brunswick',
  'Southern Methodist University',
  'Stanford University',
  'Stevens Institute of Technology',
  'Syracuse University',
  'Texas A&M University',
  'Tufts University',
  'Tulane University',
  'University at Buffalo',
  'University of Alabama',
  'University of Alberta',
  'University of Arizona',
  'University of British Columbia',
  'University of Calgary',
  'University of California, Berkeley',
  'University of California, Davis',
  'University of California, Irvine',
  'University of California, Los Angeles (UCLA)',
  'University of California, San Diego',
  'University of California, Santa Barbara',
  'University of Chicago',
  'University of Colorado Boulder',
  'University of Connecticut',
  'University of Delaware',
  'University of Florida',
  'University of Georgia',
  'University of Illinois at Urbana-Champaign',
  'University of Iowa',
  'University of Maryland, College Park',
  'University of Massachusetts Amherst',
  'University of Miami',
  'University of Michigan',
  'University of Minnesota Twin Cities',
  'University of Missouri',
  'University of Montreal',
  'University of New Hampshire',
  'University of North Carolina at Chapel Hill',
  'University of Notre Dame',
  'University of Oregon',
  'University of Pennsylvania',
  'University of Pittsburgh',
  'University of Rochester',
  'University of San Diego',
  'University of San Francisco',
  'University of South Carolina',
  'University of Southern California',
  'University of Tennessee',
  'University of Texas at Austin',
  'University of Toronto',
  'University of Tulsa',
  'University of Utah',
  'University of Vermont',
  'University of Virginia',
  'University of Washington',
  'University of Waterloo',
  'University of Wisconsin-Madison',
  'Vanderbilt University',
  'Villanova University',
  'Virginia Tech',
  'Wake Forest University',
  'Washington University in St. Louis',
  'Western University',
  'Worcester Polytechnic Institute',
  'Yale University',
  'Yeshiva University',
  'Other',
];
