export const antdTheme = {
  token: {
    colorPrimary: '#1C24E6',
    colorBgContainer: '#ffffff',
    colorBgElevated: '#ffffff',
    colorBorder: '#E6E6E6',
    colorText: '#1A1A1A',
    colorTextSecondary: '#b3b3b3',
    colorTextTertiary: '#4B5563',
    colorTextQuaternary: '#808080',
    controlItemBgActive: '#E9E9E9',
    colorError: '#FF2828',
    colorSuccess: '#00B612',
  },
  components: {
    Select: {
      colorBgContainer: '#ffffff',
      colorBorder: '#E9E9E9',
      colorText: '#000000',
      optionSelectedBg: '#F5F5F5',
    },
    DatePicker: {
      hoverBorderColor: '#E6E6E6',
      activeBorderColor: '#808080',
      cellHoverWithRangeBg: '#ffffff',
      cellRangeBorderColor: '#E9E9E9',
    },
    Tabs: {
      colorBgContainer: '#ffffff',
      colorBorder: '#E9E9E9',
      colorText: '#000000',
      optionSelectedBg: '#F5F5F5',
      horizontalItemGutter: 140,
    },
    Modal: {
      contentBg: '#ffffff', // Changed to light color
      colorBorder: '#E9E9E9',
      colorText: '#000000',
      footerBg: 'transparent',
      titleColor: 'rgba(0, 0, 0, 0.88)',
      titleFontSize: 16,
      titleLineHeight: 1.5,
    },
    Button: {
      colorText: '#FFFFFF',
      colorBgContainer: '#1A1A1A',
      defaultActiveColor: '#E0E0E0',
      defaultHoverColor: '#FFFFFF',
      defaultHoverBg: '#1C24E6',
      defaultHoverBorderColor: '#1A1A1A',
      dangerColor: '#FFFFFF',
      primaryShadow: '0',
      defaultShadow: '0',
      defaultBorderColor: '#F8F8F8',
    },
    InputNumber: {
      borderColor: '#E7E7E7',
      focusBorderColor: '#000000',
      hoverBorderColor: '#b3b3b3',
      backgroundColor: '#ffffff',
      textColor: '#1A1A1A',
      placeholderColor: '#808080',
      numberInputArrowColor: '#4d4d4d',
    },
    Form: {
      labelColor: '#4B5563',
      labelHeight: 0,
      verticalLabelPadding: 0,
    },
    Collapse: {
      contentBg: '#ffffff',
      headerBg: 'rgba(0, 0, 0, 0)',
      contentPadding: '16px 0px',
      headerPadding: '16px 0px',
    },
    TreeSelect: {
      titleHeight: 24,
    },
  },
};
